# Generated by Django 5.2.8 on 2025-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_post_list',
            field=models.BooleanField(default=True),
        ),
    ]
