# Generated by Django 5.2.8 on 2025-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_sitesetup_show_about_sitesetup_show_post_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_post_miniature_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
