# Generated by Django 5.2.8 on 2025-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_sitesetup_about_sitesetup_show_post_miniature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
