# Generated by Django 5.2.8 on 2025-11-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_alter_sitesetup_description_alter_sitesetup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='site_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_links', to='site_setup.sitesetup'),
        ),
    ]
